/**
 * GitHub Actions CI/CD workflow generator (ADR-017).
 * Generates ci.yml (test + lint on PR) and deploy.yml (deploy on merge to main).
 * Framework-aware: Node → npm test, Django → pytest, Rails → rspec.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getBuildOutputDir } from './build-step.js';

interface CIConfig {
  runtime: 'node' | 'python' | 'ruby';
  nodeVersion: string;
  pythonVersion: string;
  rubyVersion: string;
  installCommand: string;
  buildCommand: string;
  testCommand: string;
  lintCommand: string;
}

const FRAMEWORK_CI: Record<string, Partial<CIConfig>> = {
  'next.js':   { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'express':   { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'vite':      { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'nuxt':      { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'remix':     { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'svelte':    { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'sveltekit': { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'astro':     { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'gatsby':    { runtime: 'node', buildCommand: 'npm run build', testCommand: 'npm run test --if-present', lintCommand: 'npm run lint --if-present' },
  'django':    { runtime: 'python', installCommand: 'pip install -r requirements.txt', buildCommand: 'python manage.py collectstatic --noinput', testCommand: 'pytest', lintCommand: 'flake8 --max-line-length=120 || true' },
  'flask':     { runtime: 'python', installCommand: 'pip install -r requirements.txt', testCommand: 'pytest', lintCommand: 'flake8 --max-line-length=120 || true' },
  'rails':     { runtime: 'ruby', installCommand: 'bundle install', buildCommand: 'bundle exec rails assets:precompile', testCommand: 'bundle exec rspec', lintCommand: 'bundle exec rubocop --format simple || true' },
};

/** Check if a framework has an explicit build command (not a default fallback). */
function hasBuildCommand(framework: string): boolean {
  return !!(FRAMEWORK_CI[framework]?.buildCommand);
}

function resolveConfig(framework: string): CIConfig {
  const partial = FRAMEWORK_CI[framework] || {};
  return {
    runtime: partial.runtime || 'node',
    nodeVersion: '20',
    pythonVersion: '3.12',
    rubyVersion: '3.3',
    installCommand: partial.installCommand || 'npm ci',
    buildCommand: partial.buildCommand || 'npm run build',
    testCommand: partial.testCommand || 'npm run test --if-present',
    lintCommand: partial.lintCommand || 'npm run lint --if-present',
  };
}

function generateSetupSteps(config: CIConfig): string {
  switch (config.runtime) {
    case 'python':
      return `      - uses: actions/setup-python@v5
        with:
          python-version: '${config.pythonVersion}'
      - run: ${config.installCommand}`;
    case 'ruby':
      return `      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${config.rubyVersion}'
          bundler-cache: true`;
    default:
      return `      - uses: actions/setup-node@v4
        with:
          node-version: '${config.nodeVersion}'
          cache: 'npm'
      - run: npm ci`;
  }
}

function generateCIWorkflow(framework: string): string {
  const config = resolveConfig(framework);
  const setup = generateSetupSteps(config);

  return `# CI — test + lint on pull request
# Generated by VoidForge (ADR-017)
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${setup}
      - run: ${config.testCommand}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${setup}
      - run: ${config.lintCommand}
`;
}

/** Map deploy targets to their required GitHub secrets for documentation. */
const DEPLOY_SECRETS: Record<string, string[]> = {
  vercel: ['VERCEL_TOKEN', 'VERCEL_ORG_ID', 'VERCEL_PROJECT_ID'],
  cloudflare: ['CLOUDFLARE_API_TOKEN', 'CF_PROJECT_NAME'],
  railway: [],
  vps: ['SSH_PRIVATE_KEY', 'SSH_USER', 'SSH_HOST'],
  static: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION', 'S3_BUCKET'],
};

function generateDeployWorkflow(framework: string, deployTarget: string): string {
  const config = resolveConfig(framework);
  const setup = generateSetupSteps(config);

  let deployStep: string;
  switch (deployTarget) {
    case 'vercel':
      deployStep = `      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'`;
      break;
    case 'cloudflare': {
      const cfOutputDir = getBuildOutputDir(framework);
      deployStep = `      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./${cfOutputDir} --project-name=\${{ secrets.CF_PROJECT_NAME }}`;
      break;
    }
    case 'railway':
      deployStep = `      # Railway auto-deploys on push — this job just verifies the build
      - run: echo "Railway auto-deploy triggered by push to main"`;
      break;
    case 'vps': {
      const vpsBuild = config.runtime === 'python'
        ? 'pip install -r requirements.txt && python manage.py collectstatic --noinput && sudo systemctl restart gunicorn'
        : config.runtime === 'ruby'
          ? 'bundle install && bundle exec rails assets:precompile && sudo systemctl restart puma'
          : 'npm ci && npm run build && pm2 restart all';
      deployStep = `      - run: |
          mkdir -p ~/.ssh
          echo "\${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          ssh -i ~/.ssh/deploy-key.pem -o StrictHostKeyChecking=accept-new \${{ secrets.SSH_USER }}@\${{ secrets.SSH_HOST }} "cd /opt/app/current && git pull && ${vpsBuild}"
          rm -f ~/.ssh/deploy-key.pem`;
      break;
    }
    case 'static': {
      const s3OutputDir = getBuildOutputDir(framework);
      deployStep = `      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: \${{ secrets.AWS_REGION }}
      - run: aws s3 sync ./${s3OutputDir} s3://\${{ secrets.S3_BUCKET }} --delete`;
      break;
    }
    default:
      deployStep = `      - run: echo "Deploy step not configured for target: ${deployTarget}"`;
  }

  const secrets = DEPLOY_SECRETS[deployTarget] || [];
  const secretsDoc = secrets.length > 0
    ? `# Required secrets (set in GitHub repo > Settings > Secrets and variables > Actions):\n${secrets.map(s => `#   - ${s}`).join('\n')}\n`
    : '';

  return `# Deploy — build and deploy on merge to main
# Generated by VoidForge (ADR-017)
${secretsDoc}name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${setup}
${hasBuildCommand(framework) ? `      - run: ${config.buildCommand}\n` : ''}${deployStep}
`;
}

export interface CIGeneratorResult {
  success: boolean;
  files: string[];
  error?: string;
}

/**
 * Generate CI/CD workflow files in the project's .github/workflows/ directory.
 */
export async function generateCIWorkflows(
  projectDir: string,
  framework: string,
  deployTarget: string,
): Promise<CIGeneratorResult> {
  const workflowDir = join(projectDir, '.github', 'workflows');
  const files: string[] = [];

  try {
    await mkdir(workflowDir, { recursive: true });

    const ciContent = generateCIWorkflow(framework);
    await writeFile(join(workflowDir, 'ci.yml'), ciContent, 'utf-8');
    files.push('.github/workflows/ci.yml');

    const deployContent = generateDeployWorkflow(framework, deployTarget);
    await writeFile(join(workflowDir, 'deploy.yml'), deployContent, 'utf-8');
    files.push('.github/workflows/deploy.yml');

    return { success: true, files };
  } catch (err) {
    return { success: false, files, error: (err as Error).message };
  }
}
