/**
 * Startup environment validation script generator (ADR-018).
 * Generates a script that checks required env vars at boot time.
 * No dependencies — pure Node.js stdlib or Python stdlib.
 */

import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';

/** Patterns that indicate a placeholder value, not a real value. */
const PLACEHOLDER_PATTERNS = [
  /^#\s*pending/i,
  /^#\s*check/i,
  /^your[-_]?\w+[-_]?here$/i,
  /^TODO/i,
  /^CHANGE[-_]?ME/i,
  /^xxx/i,
  /^\s*$/,
];

function isPlaceholder(value: string): boolean {
  return PLACEHOLDER_PATTERNS.some(p => p.test(value));
}

/**
 * Parse a .env file and extract variable names and whether their values are real.
 * Comments-only lines and section headers are skipped.
 */
function parseEnvFile(content: string): { key: string; hasValue: boolean }[] {
  const vars: { key: string; hasValue: boolean }[] = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip matching quotes only (both must be the same character)
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Skip VoidForge metadata keys
    if (key.startsWith('VERCEL_PROJECT_') || key.startsWith('CF_PROJECT_') || key.startsWith('RAILWAY_PROJECT_')) continue;

    vars.push({ key, hasValue: !isPlaceholder(value) });
  }
  return vars;
}

function generateNodeValidator(vars: { key: string; hasValue: boolean }[]): string {
  const requiredKeys = vars.map(v => `  '${v.key}'`).join(',\n');
  const pendingKeys = vars.filter(v => !v.hasValue).map(v => `  '${v.key}'`).join(',\n');

  return `#!/usr/bin/env node
/**
 * Startup environment validation — checks required env vars before boot.
 * Generated by VoidForge (ADR-018).
 * Usage: node validate-env.js
 * Works in both CommonJS and ESM projects.
 */

const required = [
${requiredKeys}
];

const PLACEHOLDER_PATTERNS = [
  /^#\\s*pending/i,
  /^#\\s*check/i,
  /^your[-_]?\\w+[-_]?here$/i,
  /^TODO/i,
  /^CHANGE[-_]?ME/i,
  /^xxx/i,
];

function isPlaceholder(val) {
  return !val.trim() || PLACEHOLDER_PATTERNS.some(p => p.test(val));
}

function validateEnv() {
  const missing = [];
  const empty = [];

  for (const key of required) {
    const val = process.env[key];
    if (val === undefined) {
      missing.push(key);
    } else if (isPlaceholder(val)) {
      empty.push(key);
    }
  }

  if (missing.length > 0 || empty.length > 0) {
    console.error('\\n=== Environment Validation Failed ===\\n');
    if (missing.length > 0) {
      console.error('Missing variables:');
      for (const key of missing) console.error('  - ' + key);
    }
    if (empty.length > 0) {
      console.error('Placeholder values (need real values):');
      for (const key of empty) console.error('  - ' + key + ' (placeholder value detected)');
    }
    console.error('\\nSet these in your .env file or environment before starting the app.\\n');
    process.exit(1);
  }

  console.log('Environment validation passed (' + required.length + ' vars checked)');
}

// Run if called directly — works in both CJS and ESM
const isMain = typeof require !== 'undefined'
  ? require.main === module
  : process.argv[1]?.endsWith('validate-env.js');

if (isMain) {
  // Load .env if dotenv is available
  try { require('dotenv').config(); } catch { /* dotenv not installed — using process.env */ }
  validateEnv();
}

// Export for programmatic use
if (typeof module !== 'undefined') module.exports = { validateEnv };
`;
}

function generatePythonValidator(vars: { key: string; hasValue: boolean }[]): string {
  const requiredList = vars.map(v => `    "${v.key}"`).join(',\n');

  return `#!/usr/bin/env python3
"""
Startup environment validation — checks required env vars before boot.
Generated by VoidForge (ADR-018).
Usage: python validate_env.py
"""

import os
import sys

REQUIRED = [
${requiredList}
]

PLACEHOLDER_PREFIXES = ["# pending", "# check", "TODO", "CHANGE_ME", "xxx"]


def validate_env():
    missing = []
    empty = []

    for key in REQUIRED:
        val = os.environ.get(key)
        if val is None:
            missing.append(key)
        elif not val.strip() or any(val.startswith(p) for p in PLACEHOLDER_PREFIXES):
            empty.append(key)

    if missing or empty:
        print("\\n=== Environment Validation Failed ===\\n", file=sys.stderr)
        if missing:
            print("Missing variables:", file=sys.stderr)
            for key in missing:
                print(f"  - {key}", file=sys.stderr)
        if empty:
            print("Placeholder values (need real values):", file=sys.stderr)
            for key in empty:
                print(f"  - {key} (placeholder value detected)", file=sys.stderr)
        print("\\nSet these in your .env file or environment before starting the app.\\n", file=sys.stderr)
        sys.exit(1)

    print(f"Environment validation passed ({len(REQUIRED)} vars checked)")


if __name__ == "__main__":
    # Load .env if python-dotenv is available
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    validate_env()
`;
}

export interface EnvValidatorResult {
  success: boolean;
  file: string;
  error?: string;
}

/**
 * Generate an environment validation script based on the project's .env file.
 */
export async function generateEnvValidator(
  projectDir: string,
  framework: string,
): Promise<EnvValidatorResult> {
  const isPython = framework === 'django' || framework === 'flask';
  const filename = isPython ? 'validate_env.py' : 'validate-env.js';

  try {
    // Read the current .env file to discover required variables
    let envContent = '';
    try {
      envContent = await readFile(join(projectDir, '.env'), 'utf-8');
    } catch {
      // No .env file — generate a minimal validator
      return { success: true, file: '' };
    }

    const vars = parseEnvFile(envContent);
    if (vars.length === 0) {
      return { success: true, file: '' };
    }

    const content = isPython
      ? generatePythonValidator(vars)
      : generateNodeValidator(vars);

    await writeFile(join(projectDir, filename), content, 'utf-8');
    return { success: true, file: filename };
  } catch (err) {
    return { success: false, file: filename, error: (err as Error).message };
  }
}
