/**
 * Post-deploy health monitoring (ADR-023).
 * VPS: generates a cron-based health check script.
 * Platforms: emits dashboard links.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { ProvisionEmitter } from './provisioners/types.js';

/** Platform monitoring dashboard URL patterns. */
const DASHBOARD_URLS: Record<string, (outputs: Record<string, string>) => string | null> = {
  vercel: (o) => o['VERCEL_PROJECT_NAME']
    ? `https://vercel.com/~/projects/${o['VERCEL_PROJECT_NAME']}/analytics`
    : null,
  railway: (o) => o['RAILWAY_PROJECT_ID']
    ? `https://railway.app/project/${o['RAILWAY_PROJECT_ID']}`
    : null,
  cloudflare: (o) => o['CF_PROJECT_NAME']
    ? `https://dash.cloudflare.com/?to=/:account/pages/view/${o['CF_PROJECT_NAME']}`
    : null,
};

/**
 * Generate a VPS health check cron script.
 */
function generateHealthCheckScript(deployUrl: string, projectName: string): string {
  // Sanitize inputs for shell safety — strip anything that's not alphanumeric, dash, or dot
  const safeName = projectName.replace(/[^a-zA-Z0-9._-]/g, '-').slice(0, 64);
  const safeUrl = deployUrl.replace(/[^a-zA-Z0-9:/.?&=_-]/g, '');
  return `#!/usr/bin/env bash
# healthcheck.sh — Basic uptime monitor for ${safeName}
# Generated by VoidForge (ADR-023)
# Install: crontab -e, add: */5 * * * * /opt/app/infra/healthcheck.sh
set -euo pipefail

URL="${safeUrl}"
LOG="/var/log/${safeName}-health.log"
TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')

HTTP_CODE=\$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "\$URL" 2>/dev/null || echo "000")

if [ "\$HTTP_CODE" -ge 200 ] && [ "\$HTTP_CODE" -lt 400 ]; then
  echo "\$TIMESTAMP OK \$HTTP_CODE \$URL" >> "\$LOG"
else
  echo "\$TIMESTAMP FAIL \$HTTP_CODE \$URL" >> "\$LOG"
  # Uncomment to add email alerting:
  # echo "Health check failed: \$URL returned \$HTTP_CODE at \$TIMESTAMP" | mail -s "[ALERT] \$URL down" your@email.com
fi

# Keep log under 10k lines
tail -n 10000 "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG" 2>/dev/null || true
`;
}

export interface HealthMonitorResult {
  file?: string;
  dashboardUrl?: string;
}

/**
 * Set up post-deploy health monitoring.
 * VPS: generates health check script. Platforms: returns dashboard URL.
 */
export async function setupHealthMonitoring(
  deployTarget: string,
  projectDir: string,
  projectName: string,
  deployUrl: string,
  outputs: Record<string, string>,
  emit: ProvisionEmitter,
): Promise<HealthMonitorResult> {
  if (deployTarget === 'vps' && !deployUrl) {
    emit({ step: 'health-monitor', status: 'skipped', message: 'VPS deployed but no URL available yet — run healthcheck.sh manually after DNS propagates' });
    return {};
  }

  if (deployTarget === 'vps' && deployUrl) {
    emit({ step: 'health-monitor', status: 'started', message: 'Generating health check script' });
    try {
      const infraDir = join(projectDir, 'infra');
      await mkdir(infraDir, { recursive: true });

      const script = generateHealthCheckScript(deployUrl, projectName);
      const scriptPath = join(infraDir, 'healthcheck.sh');
      await writeFile(scriptPath, script, { mode: 0o755 });

      emit({ step: 'health-monitor', status: 'done', message: 'Generated infra/healthcheck.sh — add to crontab: */5 * * * * /opt/app/infra/healthcheck.sh' });
      return { file: 'infra/healthcheck.sh' };
    } catch (err) {
      emit({ step: 'health-monitor', status: 'error', message: 'Failed to generate health check script', detail: (err as Error).message });
      return {};
    }
  }

  if (deployTarget === 'docker') {
    emit({ step: 'health-monitor', status: 'skipped', message: 'Docker — add a healthcheck to your Dockerfile or docker-compose.yml' });
    return {};
  }

  // Platform targets — emit dashboard link
  const getDashboardUrl = DASHBOARD_URLS[deployTarget];
  if (getDashboardUrl) {
    const dashboardUrl = getDashboardUrl(outputs);
    if (dashboardUrl) {
      emit({ step: 'health-monitor', status: 'done', message: `Monitor your app: ${dashboardUrl}` });
      return { dashboardUrl };
    }
  }

  emit({ step: 'health-monitor', status: 'skipped', message: 'No monitoring configured for this target' });
  return {};
}
