/**
 * Optional Sentry error tracking integration (ADR-024).
 * Generates SDK initialization code when sentry-dsn exists in vault.
 * Framework-aware: Next.js, Express, Django.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ProvisionEmitter } from './provisioners/types.js';
import { appendEnvSection } from './env-writer.js';

function generateNodeSentry(framework: string): { filename: string; content: string; pkg: string } {
  if (framework === 'next.js') {
    return {
      filename: 'sentry.client.config.ts',
      pkg: '@sentry/nextjs',
      content: `// Sentry client-side initialization — generated by VoidForge (ADR-024)
// Install: npm install @sentry/nextjs
// See: https://docs.sentry.io/platforms/javascript/guides/nextjs/

import * as Sentry from '@sentry/nextjs';

Sentry.init({
  dsn: process.env.NEXT_PUBLIC_SENTRY_DSN || process.env.SENTRY_DSN,
  tracesSampleRate: 0.1, // 10% of transactions — increase for debugging, decrease for cost
  environment: process.env.NODE_ENV,
});
`,
    };
  }

  return {
    filename: 'sentry.ts',
    pkg: '@sentry/node',
    content: `// Sentry server-side initialization — generated by VoidForge (ADR-024)
// Install: npm install @sentry/node
// Import this file at the top of your entry point (e.g., index.ts)

import * as Sentry from '@sentry/node';

Sentry.init({
  dsn: process.env.SENTRY_DSN,
  tracesSampleRate: 0.1, // 10% of transactions — increase for debugging, decrease for cost
  environment: process.env.NODE_ENV || 'production',
});

export { Sentry };
`,
  };
}

function generatePythonSentry(framework: string): { filename: string; content: string; pkg: string } {
  if (framework === 'django') {
    return {
      filename: 'sentry_config.py',
      pkg: 'sentry-sdk[django]',
      content: `# Sentry Django initialization — generated by VoidForge (ADR-024)
# Install: pip install sentry-sdk[django]
# Add to settings.py: import sentry_config  # noqa: F401

import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""),
    integrations=[DjangoIntegration()],
    traces_sample_rate=0.1,  # 10% — increase for debugging, decrease for cost
    environment=os.environ.get("DJANGO_ENV", "production"),
)
`,
    };
  }

  return {
    filename: 'sentry_config.py',
    pkg: 'sentry-sdk[flask]',
    content: `# Sentry Flask initialization — generated by VoidForge (ADR-024)
# Install: pip install sentry-sdk[flask]
# Import at the top of your app: import sentry_config  # noqa: F401

import os
import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""),
    integrations=[FlaskIntegration()],
    traces_sample_rate=0.1,  # 10% — increase for debugging, decrease for cost
    environment=os.environ.get("FLASK_ENV", "production"),
)
`,
  };
}

export interface SentryResult {
  success: boolean;
  file?: string;
  pkg?: string;
}

/**
 * Generate Sentry initialization code if sentry-dsn exists in credentials.
 */
export async function generateSentryInit(
  projectDir: string,
  framework: string,
  sentryDsn: string | undefined,
  emit: ProvisionEmitter,
): Promise<SentryResult> {
  if (!sentryDsn) {
    emit({ step: 'sentry', status: 'skipped', message: 'No Sentry DSN in vault — error tracking skipped. Add sentry-dsn to enable.' });
    return { success: true };
  }

  emit({ step: 'sentry', status: 'started', message: 'Generating Sentry error tracking initialization' });

  const isPython = framework === 'django' || framework === 'flask';

  try {
    const config = isPython
      ? generatePythonSentry(framework)
      : generateNodeSentry(framework);

    await writeFile(join(projectDir, config.filename), config.content, 'utf-8');

    // Write SENTRY_DSN to .env so the generated code can read it
    await appendEnvSection(projectDir, [
      `# Sentry error tracking — generated by VoidForge (ADR-024)`,
      `SENTRY_DSN=${sentryDsn}`,
    ]);

    emit({ step: 'sentry', status: 'done', message: `Generated ${config.filename} — install: ${isPython ? 'pip' : 'npm'} install ${config.pkg}` });
    return { success: true, file: config.filename, pkg: config.pkg };
  } catch (err) {
    emit({ step: 'sentry', status: 'error', message: 'Failed to generate Sentry config', detail: (err as Error).message });
    return { success: false };
  }
}
