/**
 * Template: Caddyfile — reverse proxy + automatic HTTPS + security headers.
 * Written to projectDir/infra/Caddyfile
 */

interface CaddyfileOptions {
  framework: string;
  hostname?: string;
}

export function generateCaddyfile(opts: CaddyfileOptions): string {
  const port = opts.framework === 'django' ? '8000' : '3000';
  const siteAddress = opts.hostname || ':80';

  const comment = opts.hostname
    ? `# Caddyfile — Reverse proxy for ${opts.hostname}
# Generated by VoidForge
#
# Caddy will auto-provision HTTPS via Let's Encrypt.
# If using Cloudflare proxy (orange cloud), set SSL mode to "Full" in Cloudflare dashboard.
#
# Usage:
#   1. Copy to server: scp Caddyfile user@host:/etc/caddy/Caddyfile
#   2. Reload: sudo systemctl reload caddy`
    : `# Caddyfile — Reverse proxy with automatic HTTPS
# Generated by VoidForge
#
# Usage:
#   1. Replace :80 with your domain (e.g. example.com)
#   2. Copy to server: scp Caddyfile user@host:/etc/caddy/Caddyfile
#   3. Reload: sudo systemctl reload caddy
#
# Caddy auto-provisions HTTPS certificates via Let's Encrypt
# when you replace :80 with a real domain name.`;

  return `${comment}

${siteAddress} {
    reverse_proxy localhost:${port}

    # Security headers
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        Permissions-Policy "camera=(), microphone=(), geolocation=()"
        Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'"
        -Server
    }

    # Gzip compression
    encode gzip

    # Access logs
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
`;
}
