/**
 * Template: deploy.sh — release-directory deploy with health check + auto-rollback.
 * Uses timestamped release dirs with a "current" symlink for atomic deploys.
 * Written to projectDir/infra/deploy.sh
 */

interface DeployScriptOptions {
  framework: string;
}

export function generateDeployScript(opts: DeployScriptOptions): string {
  const isNode = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const isDjango = opts.framework === 'django';

  let installCommands: string;
  let restartCommands: string;
  let healthPath = '/';

  if (isNode) {
    installCommands = 'npm ci --production --ignore-scripts';
    restartCommands = 'pm2 startOrRestart /opt/app/current/ecosystem.config.js --env production && pm2 save';
  } else if (isDjango) {
    installCommands = 'pip3.12 install -r requirements.txt';
    restartCommands = 'python3.12 manage.py migrate --noinput && python3.12 manage.py collectstatic --noinput && supervisorctl restart app';
  } else {
    installCommands = 'bundle install --deployment --without development test';
    restartCommands = 'RAILS_ENV=production bundle exec rails db:migrate && touch tmp/restart.txt';
  }

  return `#!/usr/bin/env bash
# deploy.sh — Release-directory deploy with health check + auto-rollback
# Generated by VoidForge. Reads config from .env
set -euo pipefail

# Load environment
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

SSH_HOST="\${SSH_HOST:?Set SSH_HOST in .env}"
SSH_USER="\${SSH_USER:-ec2-user}"
SSH_KEY="\${SSH_KEY_PATH:-.ssh/deploy-key.pem}"
RELEASES_DIR="/opt/app/releases"
CURRENT_LINK="/opt/app/current"
HEALTH_URL="http://localhost:3000${healthPath}"
HEALTH_RETRIES=5
HEALTH_DELAY=3

SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=accept-new"

RELEASE="$(date +%Y%m%d%H%M%S)"
RELEASE_DIR="$RELEASES_DIR/$RELEASE"

echo "=== Deploying release $RELEASE to $SSH_HOST ==="

# Create release directory
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "mkdir -p $RELEASE_DIR"

# Sync files to new release directory
rsync -avz --delete \\
  --exclude node_modules \\
  --exclude .git \\
  --exclude .env \\
  --exclude logs \\
  --exclude .ssh \\
  --exclude infra \\
  --exclude coverage \\
  -e "ssh $SSH_OPTS" \\
  ./ "$SSH_USER@$SSH_HOST:$RELEASE_DIR/"

# Install dependencies in release directory
echo "Installing dependencies..."
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $RELEASE_DIR && ${installCommands}"

# Swap symlink atomically (previous release preserved for rollback)
PREVIOUS="$(ssh $SSH_OPTS $SSH_USER@$SSH_HOST "readlink $CURRENT_LINK 2>/dev/null || echo ''")"
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "ln -sfn $RELEASE_DIR $CURRENT_LINK"

# Restart application
echo "Restarting application..."
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $CURRENT_LINK && ${restartCommands}"

# Health check with retries
echo "Running health check..."
HEALTHY=false
for i in $(seq 1 $HEALTH_RETRIES); do
  sleep $HEALTH_DELAY
  if ssh $SSH_OPTS $SSH_USER@$SSH_HOST "curl -sf $HEALTH_URL > /dev/null 2>&1"; then
    HEALTHY=true
    echo "Health check passed (attempt $i/$HEALTH_RETRIES)"
    break
  fi
  echo "Health check attempt $i/$HEALTH_RETRIES failed, retrying..."
done

if [ "$HEALTHY" = false ]; then
  echo "=== HEALTH CHECK FAILED — rolling back ==="
  if [ -n "$PREVIOUS" ]; then
    ssh $SSH_OPTS $SSH_USER@$SSH_HOST "ln -sfn $PREVIOUS $CURRENT_LINK"
    ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $CURRENT_LINK && ${restartCommands}"
    echo "Rolled back to previous release: $PREVIOUS"
  else
    echo "No previous release to roll back to!"
  fi
  exit 1
fi

# Clean up old releases (keep last 5)
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $RELEASES_DIR && ls -1d */ | head -n -5 | xargs -r rm -rf"

echo ""
echo "=== Deploy complete ==="
echo "Release: $RELEASE"
echo "App running at http://$SSH_HOST"
`;
}
