/**
 * Template: ecosystem.config.js — PM2 process manager configuration.
 * Written to projectDir/ecosystem.config.js
 */

interface EcosystemOptions {
  projectName: string;
  framework: string;
}

export function generateEcosystemConfig(opts: EcosystemOptions): string {
  const isNextjs = opts.framework === 'next.js';
  const script = isNextjs ? 'node_modules/.bin/next' : 'dist/index.js';
  const args = isNextjs ? 'start' : '';
  const instances = isNextjs ? '2' : 'max';

  return `// ecosystem.config.js — PM2 configuration
// Generated by VoidForge
module.exports = {
  apps: [
    {
      name: ${JSON.stringify(opts.projectName)},
      script: '${script}',${args ? `\n      args: '${args}',` : ''}
      instances: '${instances}',
      exec_mode: 'cluster',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_memory_restart: '512M',
      max_restarts: 10,
      min_uptime: '5s',
      listen_timeout: 10000,
      kill_timeout: 5000,
      error_file: '/opt/app/logs/error.log',
      out_file: '/opt/app/logs/out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
`;
}
