/**
 * Template: provision.sh — idempotent server setup for VPS.
 * Includes security hardening (fail2ban, SSH, firewall), swap, log rotation.
 * Written to projectDir/infra/provision.sh
 */

interface ProvisionScriptOptions {
  framework: string;
  database: string;
  cache: string;
  instanceType?: string;
  extensions?: string[];
}

// QA-001/SEC-009: Allowlist of safe PostgreSQL extensions — prevent SQL injection via extension names
const ALLOWED_EXTENSIONS = ['postgis', 'pg_trgm', 'uuid-ossp', 'pgcrypto', 'citext', 'hstore', 'ltree', 'cube', 'earthdistance', 'unaccent', 'vector', 'pg_stat_statements', 'tablefunc', 'btree_gist', 'btree_gin', 'fuzzystrmatch'];

/** Generate PostgreSQL extension install commands if extensions are specified. */
function generateExtensionBlock(opts: ProvisionScriptOptions): string {
  if (!opts.extensions || opts.extensions.length === 0 || opts.database !== 'postgres') return '';

  // Filter to only allowed extensions
  const safeExtensions = opts.extensions.filter(ext => ALLOWED_EXTENSIONS.includes(ext.toLowerCase().trim()));
  if (safeExtensions.length === 0) return '';

  const lines: string[] = [
    '',
    '# ==========================================',
    '# PostgreSQL Extensions',
    '# ==========================================',
  ];

  for (const ext of safeExtensions) {
    const extLower = ext.toLowerCase().trim();
    if (extLower === 'postgis') {
      lines.push('echo "Installing PostGIS..."');
      lines.push('dnf install -y -q postgis34_16 || apt-get install -y -q postgresql-16-postgis-3 2>/dev/null || true');
    } else if (extLower === 'pg_trgm') {
      lines.push('echo "Installing pg_trgm..."');
      lines.push('# pg_trgm is included in postgresql-contrib (usually pre-installed)');
      lines.push('dnf install -y -q postgresql16-contrib 2>/dev/null || apt-get install -y -q postgresql-contrib 2>/dev/null || true');
    }
    // CREATE EXTENSION is idempotent
    lines.push(`sudo -u postgres psql -d "$\{DB_NAME:-app}" -c "CREATE EXTENSION IF NOT EXISTS ${extLower};" 2>/dev/null || true`);
  }

  return lines.join('\n');
}

export function generateProvisionScript(opts: ProvisionScriptOptions): string {
  const nodeSetup = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const pythonSetup = opts.framework === 'django';
  const rubySetup = opts.framework === 'rails';

  let runtimeInstall = '';
  if (nodeSetup) {
    runtimeInstall = `
# Install Node.js 20.x
if ! command -v node &>/dev/null; then
  echo "Installing Node.js..."
  curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
  dnf install -y nodejs
fi
echo "Node.js $(node --version)"

# Install PM2 globally
if ! command -v pm2 &>/dev/null; then
  npm install -g pm2
fi
echo "PM2 $(pm2 --version)"

# Set up PM2 to start on boot
pm2 startup systemd -u appuser --hp /opt/app 2>/dev/null || true`;
  } else if (pythonSetup) {
    runtimeInstall = `
# Install Python 3.12
if ! command -v python3.12 &>/dev/null; then
  echo "Installing Python 3.12..."
  dnf install -y python3.12 python3.12-pip
fi
echo "Python $(python3.12 --version)"

# Install gunicorn + supervisor
pip3.12 install --quiet gunicorn supervisor`;
  } else if (rubySetup) {
    runtimeInstall = `
# Install Ruby
if ! command -v ruby &>/dev/null; then
  echo "Installing Ruby..."
  dnf install -y ruby ruby-devel
fi
echo "Ruby $(ruby --version)"

# Install bundler
gem install bundler --no-document`;
  }

  return `#!/usr/bin/env bash
# provision.sh — Idempotent VPS setup with security hardening
# Generated by VoidForge. Safe to re-run.
set -euo pipefail

echo "=== VoidForge VPS Provisioning ==="

# Update system
echo "Updating packages..."
dnf update -y -q

# Install essentials
dnf install -y -q git curl wget tar unzip
${runtimeInstall}

# Install Caddy (reverse proxy + auto HTTPS)
if ! command -v caddy &>/dev/null; then
  echo "Installing Caddy..."
  dnf install -y 'dnf-command(copr)'
  dnf copr enable -y @caddy/caddy
  dnf install -y caddy
  systemctl enable caddy
fi
echo "Caddy $(caddy version)"

# ==========================================
# Security Hardening
# ==========================================

# Install and configure fail2ban
echo "Configuring fail2ban..."
dnf install -y -q fail2ban
cat > /etc/fail2ban/jail.local << 'JAIL'
[sshd]
enabled = true
port = ssh
filter = sshd
maxretry = 5
bantime = 3600
findtime = 600
JAIL
systemctl enable --now fail2ban

# Harden SSH — disable root login and password auth
echo "Hardening SSH..."
sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl reload sshd

# Enable unattended security updates
echo "Enabling automatic security updates..."
dnf install -y -q dnf-automatic
sed -i 's/^apply_updates.*/apply_updates = yes/' /etc/dnf/automatic.conf
systemctl enable --now dnf-automatic-install.timer

# ==========================================
# Application Setup
# ==========================================

# Create app directories (release-directory structure)
APP_DIR="/opt/app"
mkdir -p "$APP_DIR/releases" "$APP_DIR/logs"

# Create app user if not exists
if ! id -u appuser &>/dev/null; then
  useradd --system --home-dir "$APP_DIR" --shell /bin/bash appuser
fi
chown -R appuser:appuser "$APP_DIR"

# ==========================================
# Firewall — lock down then open
# ==========================================
echo "Configuring firewall..."
if command -v firewall-cmd &>/dev/null; then
  firewall-cmd --set-default-zone=drop 2>/dev/null || true
  firewall-cmd --permanent --add-service=ssh 2>/dev/null || true
  firewall-cmd --permanent --add-service=http 2>/dev/null || true
  firewall-cmd --permanent --add-service=https 2>/dev/null || true
  firewall-cmd --reload 2>/dev/null || true
fi

# ==========================================
# Swap (prevents OOM during builds)
# ==========================================
${opts.instanceType === 't3.large' ? '# Swap skipped — t3.large has 8 GiB RAM' : `if [ ! -f /swapfile ]; then
  echo "Setting up ${opts.instanceType === 't3.medium' ? '1GB' : '2GB'} swap..."
  fallocate -l ${opts.instanceType === 't3.medium' ? '1G' : '2G'} /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi`}

# ==========================================
# Log Rotation
# ==========================================
cat > /etc/logrotate.d/voidforge << 'LOGROTATE'
/opt/app/logs/*.log {
  daily
  rotate 14
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
LOGROTATE

${generateExtensionBlock(opts)}
echo ""
echo "=== Provisioning complete ==="
echo "App directory: $APP_DIR/releases/ (symlinked via $APP_DIR/current)"
echo "App user: appuser"
echo "Security: fail2ban active, SSH hardened, firewall locked down"
echo "Next: run deploy.sh to deploy your app"
`;
}
