/**
 * Template: rollback.sh — swap to previous release directory.
 * Compatible with deploy.sh's release-directory strategy.
 * Written to projectDir/infra/rollback.sh
 */

interface RollbackScriptOptions {
  framework: string;
}

export function generateRollbackScript(opts: RollbackScriptOptions): string {
  const isNode = ['next.js', 'express'].includes(opts.framework) || !opts.framework;
  const isDjango = opts.framework === 'django';

  let restartCommands: string;
  if (isNode) {
    restartCommands = 'pm2 startOrRestart /opt/app/current/ecosystem.config.js --env production && pm2 save';
  } else if (isDjango) {
    restartCommands = 'python3.12 manage.py migrate --noinput && supervisorctl restart app';
  } else {
    restartCommands = 'RAILS_ENV=production bundle exec rails db:migrate && touch tmp/restart.txt';
  }

  return `#!/usr/bin/env bash
# rollback.sh — Roll back to the previous release
# Generated by VoidForge. Uses release-directory strategy.
set -euo pipefail

# Load environment
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

SSH_HOST="\${SSH_HOST:?Set SSH_HOST in .env}"
SSH_USER="\${SSH_USER:-ec2-user}"
SSH_KEY="\${SSH_KEY_PATH:-.ssh/deploy-key.pem}"
RELEASES_DIR="/opt/app/releases"
CURRENT_LINK="/opt/app/current"

SSH_OPTS="-i $SSH_KEY -o StrictHostKeyChecking=accept-new"

echo "=== Rolling back on $SSH_HOST ==="

# Find current and previous releases
CURRENT="$(ssh $SSH_OPTS $SSH_USER@$SSH_HOST "readlink $CURRENT_LINK 2>/dev/null || echo ''")"
RELEASES="$(ssh $SSH_OPTS $SSH_USER@$SSH_HOST "ls -1d $RELEASES_DIR/*/ 2>/dev/null | sort")"
PREVIOUS="$(echo "$RELEASES" | grep -B1 "$(basename "$CURRENT")" | head -1)"

if [ -z "$PREVIOUS" ] || [ "$PREVIOUS" = "$CURRENT" ]; then
  echo "No previous release to roll back to!"
  echo "Available releases:"
  ssh $SSH_OPTS $SSH_USER@$SSH_HOST "ls -1d $RELEASES_DIR/*/ 2>/dev/null"
  exit 1
fi

echo "Current:  $(basename "$CURRENT")"
echo "Rolling back to: $(basename "$PREVIOUS")"

# Swap symlink
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "ln -sfn $PREVIOUS $CURRENT_LINK"

# Restart
ssh $SSH_OPTS $SSH_USER@$SSH_HOST "cd $CURRENT_LINK && ${restartCommands}"

echo ""
echo "=== Rollback complete ==="
echo "Now running: $(basename "$PREVIOUS")"
echo "Run deploy.sh to re-deploy the latest code."
`;
}
