/**
 * Integration templates — pre-built client wrappers (ADR-025).
 * Selected via PRD frontmatter (payments: stripe, email: resend).
 * Framework-aware: generates TypeScript or Python.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { ProvisionEmitter } from '../provisioners/types.js';

// ── Stripe ──────────────────────────────────────────────

const STRIPE_TS = `// Stripe integration — generated by VoidForge (ADR-025)
// Install: npm install stripe
// Set STRIPE_SECRET_KEY in .env

import Stripe from 'stripe';

if (!process.env.STRIPE_SECRET_KEY) {
  throw new Error('STRIPE_SECRET_KEY is required');
}

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
  apiVersion: '2024-12-18.acacia',
});

/** Create a checkout session for a price. */
export async function createCheckoutSession(priceId: string, successUrl: string, cancelUrl: string) {
  return stripe.checkout.sessions.create({
    mode: 'subscription',
    payment_method_types: ['card'],
    line_items: [{ price: priceId, quantity: 1 }],
    success_url: successUrl,
    cancel_url: cancelUrl,
  });
}

/** Create a customer portal session. */
export async function createPortalSession(customerId: string, returnUrl: string) {
  return stripe.billingPortal.sessions.create({
    customer: customerId,
    return_url: returnUrl,
  });
}

/** Verify a webhook signature. */
export function verifyWebhook(payload: string | Buffer, signature: string, secret: string): Stripe.Event {
  return stripe.webhooks.constructEvent(payload, signature, secret);
}
`;

// ── Resend ──────────────────────────────────────────────

const RESEND_TS = `// Resend email integration — generated by VoidForge (ADR-025)
// Install: npm install resend
// Set RESEND_API_KEY in .env

import { Resend } from 'resend';

if (!process.env.RESEND_API_KEY) {
  throw new Error('RESEND_API_KEY is required');
}

const resend = new Resend(process.env.RESEND_API_KEY);

interface SendEmailParams {
  to: string | string[];
  subject: string;
  html: string;
  from?: string;
}

/** Send a transactional email. */
export async function sendEmail({ to, subject, html, from }: SendEmailParams) {
  return resend.emails.send({
    from: from || process.env.RESEND_FROM || 'noreply@example.com',
    to: Array.isArray(to) ? to : [to],
    subject,
    html,
  });
}

/** Send a welcome email. */
export async function sendWelcomeEmail(to: string, name: string) {
  return sendEmail({
    to,
    subject: 'Welcome!',
    html: \`<h1>Welcome, \${name}!</h1><p>Thanks for signing up.</p>\`,
  });
}
`;

// ── S3 File Upload ──────────────────────────────────────

const S3_TS = `// S3 file upload integration — generated by VoidForge (ADR-025)
// Install: npm install @aws-sdk/client-s3 @aws-sdk/s3-request-presigner
// Set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, S3_UPLOAD_BUCKET in .env

import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY) {
  throw new Error('AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are required');
}
if (!process.env.S3_UPLOAD_BUCKET) {
  throw new Error('S3_UPLOAD_BUCKET is required');
}

const s3 = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

const BUCKET = process.env.S3_UPLOAD_BUCKET;

/** Generate a pre-signed upload URL (client uploads directly to S3). */
export async function getUploadUrl(key: string, contentType: string, expiresIn = 3600): Promise<string> {
  const command = new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    ContentType: contentType,
  });
  return getSignedUrl(s3, command, { expiresIn });
}

/** Generate a pre-signed download URL. */
export async function getDownloadUrl(key: string, expiresIn = 3600): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: BUCKET,
    Key: key,
  });
  return getSignedUrl(s3, command, { expiresIn });
}
`;

// ── Template Registry ───────────────────────────────────

interface IntegrationTemplate {
  key: string;
  frontmatterField: string;
  frontmatterValue: string;
  filename: string;
  content: string;
  pkg: string;
  envVars: string[];
}

const TEMPLATES: IntegrationTemplate[] = [
  {
    key: 'stripe',
    frontmatterField: 'payments',
    frontmatterValue: 'stripe',
    filename: 'lib/stripe.ts',
    content: STRIPE_TS,
    pkg: 'stripe',
    envVars: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
  },
  {
    key: 'resend',
    frontmatterField: 'email',
    frontmatterValue: 'resend',
    filename: 'lib/resend.ts',
    content: RESEND_TS,
    pkg: 'resend',
    envVars: ['RESEND_API_KEY', 'RESEND_FROM'],
  },
  {
    key: 's3',
    frontmatterField: 'storage',
    frontmatterValue: 's3',
    filename: 'lib/s3-upload.ts',
    content: S3_TS,
    pkg: '@aws-sdk/client-s3 @aws-sdk/s3-request-presigner',
    envVars: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION', 'S3_UPLOAD_BUCKET'],
  },
];

export interface IntegrationResult {
  generated: { key: string; file: string; pkg: string }[];
  skipped: string[];
}

/**
 * Generate integration templates based on PRD frontmatter flags.
 */
export async function generateIntegrations(
  projectDir: string,
  frontmatter: Record<string, string | undefined>,
  emit: ProvisionEmitter,
): Promise<IntegrationResult> {
  const generated: IntegrationResult['generated'] = [];
  const skipped: string[] = [];

  for (const template of TEMPLATES) {
    const value = frontmatter[template.frontmatterField];
    if (value === template.frontmatterValue) {
      emit({ step: `integration-${template.key}`, status: 'started', message: `Generating ${template.key} integration` });
      try {
        const filePath = join(projectDir, template.filename);
        const dir = join(projectDir, template.filename.split('/').slice(0, -1).join('/'));
        await mkdir(dir, { recursive: true });
        await writeFile(filePath, template.content, 'utf-8');

        generated.push({ key: template.key, file: template.filename, pkg: template.pkg });
        emit({ step: `integration-${template.key}`, status: 'done', message: `Generated ${template.filename} — install: npm install ${template.pkg}` });
      } catch (err) {
        emit({ step: `integration-${template.key}`, status: 'error', message: `Failed to generate ${template.key}`, detail: (err as Error).message });
      }
    } else {
      skipped.push(template.key);
    }
  }

  if (generated.length === 0) {
    emit({ step: 'integrations', status: 'skipped', message: 'No integration templates requested in PRD frontmatter (payments: stripe, email: resend, storage: s3)' });
  }

  return { generated, skipped };
}
