/**
 * OpenAPI/Swagger spec generation (ADR-025).
 * Generates a starter OpenAPI spec from framework conventions.
 * Framework-aware: Express, Next.js API routes.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { ProvisionEmitter } from '../provisioners/types.js';

function generateOpenAPISpec(projectName: string, framework: string): string {
  const isNextjs = framework === 'next.js';
  // Strip YAML-unsafe characters — only allow alphanumeric, spaces, hyphens, underscores
  const safeName = projectName.replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 100) || 'My Project';

  return `# OpenAPI Specification
# Generated by VoidForge (ADR-025)
# Edit this file to document your API endpoints
# Serve with: npx swagger-ui-express (Express) or next-swagger-doc (Next.js)

openapi: "3.1.0"
info:
  title: "${safeName} API"
  version: "1.0.0"
  description: "API documentation for ${safeName}"

servers:
  - url: http://localhost:${isNextjs ? '3000' : '3001'}
    description: Development server

paths:
  /api/health:
    get:
      summary: Health check
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time

  # Add your API endpoints below
  # Example:
  # /api/users:
  #   get:
  #     summary: List users
  #     parameters:
  #       - in: query
  #         name: page
  #         schema:
  #           type: integer
  #           default: 1
  #     responses:
  #       "200":
  #         description: List of users
`;
}

export interface OpenAPIResult {
  success: boolean;
  file: string;
  error?: string;
}

/**
 * Generate an OpenAPI spec file for the project.
 */
export async function generateOpenAPIDoc(
  projectDir: string,
  projectName: string,
  framework: string,
  emit: ProvisionEmitter,
): Promise<OpenAPIResult> {
  emit({ step: 'openapi', status: 'started', message: 'Generating OpenAPI spec' });

  try {
    const docsDir = join(projectDir, 'docs');
    await mkdir(docsDir, { recursive: true });

    const spec = generateOpenAPISpec(projectName, framework);
    await writeFile(join(docsDir, 'api.yaml'), spec, 'utf-8');

    emit({ step: 'openapi', status: 'done', message: 'Generated docs/api.yaml — edit to document your API endpoints' });
    return { success: true, file: 'docs/api.yaml' };
  } catch (err) {
    emit({ step: 'openapi', status: 'error', message: 'Failed to generate OpenAPI spec', detail: (err as Error).message });
    return { success: false, file: '', error: (err as Error).message };
  }
}
