/**
 * Type generation from Prisma schema (ADR-025).
 * After Prisma schema changes, runs prisma generate and creates a barrel export.
 * Conditional — only runs if prisma/schema.prisma exists.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import { execCommand } from '../exec.js';
import type { ProvisionEmitter } from '../provisioners/types.js';

export interface PrismaTypesResult {
  success: boolean;
  files: string[];
  error?: string;
}

/**
 * Run prisma generate and create a barrel export for types.
 */
export async function generatePrismaTypes(
  projectDir: string,
  emit: ProvisionEmitter,
): Promise<PrismaTypesResult> {
  const schemaPath = join(projectDir, 'prisma', 'schema.prisma');

  if (!existsSync(schemaPath)) {
    emit({ step: 'prisma-types', status: 'skipped', message: 'No prisma/schema.prisma found — type generation skipped' });
    return { success: true, files: [] };
  }

  emit({ step: 'prisma-types', status: 'started', message: 'Generating Prisma types' });

  try {
    // Run prisma generate
    await execCommand('npx', ['prisma', 'generate'], {
      cwd: projectDir,
      timeout: 60_000,
    });

    // Create barrel export
    const typesDir = join(projectDir, 'types');
    await mkdir(typesDir, { recursive: true });

    const barrelContent = `// Auto-generated barrel export for Prisma types
// Re-run: npx prisma generate
// Generated by VoidForge (ADR-025)

export * from '@prisma/client';
export type { Prisma } from '@prisma/client';
`;

    await writeFile(join(typesDir, 'index.ts'), barrelContent, 'utf-8');

    emit({ step: 'prisma-types', status: 'done', message: 'Prisma types generated — import from types/index.ts' });
    return { success: true, files: ['types/index.ts'] };
  } catch (err) {
    emit({ step: 'prisma-types', status: 'error', message: 'Failed to generate Prisma types', detail: (err as Error).message });
    return { success: false, files: [], error: (err as Error).message };
  }
}
