/**
 * Database seeding script generation (ADR-025).
 * Generates seed.ts with factory functions for all Prisma models.
 * Conditional — only runs if prisma/schema.prisma exists.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import type { ProvisionEmitter } from '../provisioners/types.js';

interface SeedField {
  name: string;
  type: string;
  isOptional: boolean;
  hasDefault: boolean;
  isId: boolean;
  isRelation: boolean;
}

interface SeedModel {
  name: string;
  fields: SeedField[];
}

/** Map Prisma types to TypeScript factory values. */
const FACTORY_VALUES: Record<string, string> = {
  'String': "'Test value'",
  'Int': '1',
  'Float': '1.0',
  'Boolean': 'true',
  'DateTime': 'new Date()',
  'Json': '{}',
  'BigInt': 'BigInt(1)',
  'Decimal': '1.0',
};

function parseSeedModels(content: string): SeedModel[] {
  const models: SeedModel[] = [];
  const modelRegex = /model\s+(\w+)\s*\{([^}]+)\}/g;
  let match: RegExpExecArray | null;

  while ((match = modelRegex.exec(content)) !== null) {
    const name = match[1];
    const body = match[2];
    const fields: SeedField[] = [];

    const builtinTypes = ['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'BigInt', 'Decimal', 'Bytes'];

    for (const line of body.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('@@')) continue;

      const fieldMatch = trimmed.match(/^(\w+)\s+(\w+)(\[\])?\s*(\?)?\s*(.*)/);
      if (fieldMatch) {
        const fieldName = fieldMatch[1];
        const fieldType = fieldMatch[2];
        const isOptional = !!fieldMatch[4];
        const rest = fieldMatch[5] || '';
        const hasDefault = rest.includes('@default');
        const isId = rest.includes('@id');
        const isRelation = !builtinTypes.includes(fieldType);

        if (!isRelation && !fieldMatch[3]) { // Skip arrays (relations)
          fields.push({ name: fieldName, type: fieldType, isOptional, hasDefault, isId, isRelation });
        }
      }
    }

    models.push({ name, fields });
  }

  return models;
}

function buildSeedContent(models: SeedModel[]): string {
  const factories: string[] = [];
  const seedCalls: string[] = [];

  for (const model of models) {
    const lowerName = model.name.charAt(0).toLowerCase() + model.name.slice(1);
    const factoryFields = model.fields
      .filter(f => !f.isId && !f.hasDefault && !f.isOptional)
      .map(f => `    ${f.name}: ${FACTORY_VALUES[f.type] || "'TODO'"},`)
      .join('\n');

    factories.push(`function create${model.name}(overrides: Partial<Prisma.${model.name}CreateInput> = {}): Prisma.${model.name}CreateInput {
  return {
${factoryFields}
    ...overrides,
  };
}`);

    seedCalls.push(`  // ${model.name}
  const ${lowerName} = await prisma.${lowerName}.create({ data: create${model.name}() });
  console.log('Created ${model.name}:', ${lowerName}.id ?? '(no id)');`);
  }

  return `// Database seed script — generated by VoidForge (ADR-025)
// Run: npx tsx prisma/seed.ts
// Or: npm run seed (add "seed": "npx tsx prisma/seed.ts" to package.json scripts)

import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

// ── Factory Functions ────────────────────────────────────

${factories.join('\n\n')}

// ── Seed ─────────────────────────────────────────────────

async function seed() {
  console.log('Seeding database...');

${seedCalls.join('\n\n')}

  console.log('Seeding complete.');
}

seed()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
`;
}

export interface SeedResult {
  success: boolean;
  file: string;
  modelCount: number;
  error?: string;
}

/**
 * Generate a database seed script from the Prisma schema.
 */
export async function generateSeedScript(
  projectDir: string,
  emit: ProvisionEmitter,
): Promise<SeedResult> {
  const schemaPath = join(projectDir, 'prisma', 'schema.prisma');

  if (!existsSync(schemaPath)) {
    emit({ step: 'seed', status: 'skipped', message: 'No prisma/schema.prisma found — seed generation skipped' });
    return { success: true, file: '', modelCount: 0 };
  }

  emit({ step: 'seed', status: 'started', message: 'Generating database seed script' });

  try {
    const schema = await readFile(schemaPath, 'utf-8');
    const models = parseSeedModels(schema);

    if (models.length === 0) {
      emit({ step: 'seed', status: 'skipped', message: 'No models found in Prisma schema' });
      return { success: true, file: '', modelCount: 0 };
    }

    const prismaDir = join(projectDir, 'prisma');
    await mkdir(prismaDir, { recursive: true });

    const script = buildSeedContent(models);
    await writeFile(join(prismaDir, 'seed.ts'), script, 'utf-8');

    emit({ step: 'seed', status: 'done', message: `Generated prisma/seed.ts — ${models.length} model factories. Run: npx tsx prisma/seed.ts` });
    return { success: true, file: 'prisma/seed.ts', modelCount: models.length };
  } catch (err) {
    emit({ step: 'seed', status: 'error', message: 'Failed to generate seed script', detail: (err as Error).message });
    return { success: false, file: '', modelCount: 0, error: (err as Error).message };
  }
}
